# Generated by Django 6.0.3 on 2026-04-04 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("owner", models.CharField(max_length=100)),
                ("max_requests_per_minute", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
